# Generated by Django 5.1.9 on 2025-05-11 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="google_calendar_event_id",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar event ID for syncing. Leave blank to create new event.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="parent_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent location (e.g., a city that contains \
                    multiple neighborhoods)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_locations",
                to="events.location",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
