# Generated by Django 5.2 on 2025-04-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="events", to="events.tag"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
