# Generated by Django 5.2 on 2025-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_contact_email_alter_event_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="registration_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
