# Generated by Django 5.2 on 2025-04-30 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_event_registration_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Optional end date for multi-day events",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent event (e.g., a walk that is part of a festival)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_events",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="events", to="events.tag"),
        ),
    ]
