# Generated by Django 5.1.9 on 2025-05-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_location_parent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='calendar_id',
            field=models.CharField(blank=True, help_text='Google Calendar ID for this tag/category (for subscriptions, embeds, and iCal feeds)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='share_id',
            field=models.CharField(blank=True, help_text='Special id for sharing the google calendar.', max_length=255, null=True),
        ),
    ]
