# Generated by Django 5.2 on 2025-05-01 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_event_end_date_event_parent_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Check this box to mark the event as featured"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="primary_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="The main tag that determines the event's color",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_events",
                to="events.tag",
            ),
        ),
    ]
