# Generated by Django 5.2 on 2025-05-01 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_featured_event_primary_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="tags",
        ),
        migrations.AddField(
            model_name="event",
            name="secondary_tag",
            field=models.ForeignKey(
                blank=True,
                help_text="An optional secondary classification for the event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_events",
                to="events.tag",
            ),
        ),
    ]
