# Generated by Django 5.2 on 2025-05-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_remove_event_created_at_remove_event_parent_event_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_date", "start_time"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="hosting_organization",
            new_name="organization",
        ),
        migrations.RemoveField(
            model_name="event",
            name="registration_link",
        ),
        migrations.RemoveField(
            model_name="event",
            name="website",
        ),
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.RemoveField(
            model_name="location",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="location",
            name="organizations",
        ),
        migrations.RemoveField(
            model_name="location",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="location",
            name="website",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="website",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="slug",
        ),
        migrations.AlterField(
            model_name="event",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="external_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#007bff", max_length=7),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
