# Generated by Django 5.2 on 2025-05-05 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0008_alter_event_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent event (e.g., a walk that is part of a festival)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_events",
                to="events.event",
            ),
        ),
    ]
