# Generated by Django 5.2 on 2025-05-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0009_event_parent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="registration_link",
            field=models.URLField(
                blank=True, help_text="Link to event registration page", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.URLField(
                blank=True, help_text="Event website or more information URL", null=True
            ),
        ),
    ]
