# Generated by Django 5.1.8 on 2025-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_event_registration_link_event_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
