# Generated by Django 5.1.8 on 2025-05-07 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_communityannouncement_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="color",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="parent_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent location (e.g., a city that contains multiple \
                    neighborhoods)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_locations",
                to="events.location",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.location",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_organizations",
                to="events.organization",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
