# Generated by Django 5.1.8 on 2025-05-07 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_remove_tag_color_location_latitude_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="contact_email",
            new_name="email",
        ),
    ]
