# Generated by Django 5.1.8 on 2025-05-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_rename_contact_email_event_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="exclude_from_calendar",
            field=models.BooleanField(
                default=False,
                help_text="Exclude this event from the calendar and event list.",
            ),
        ),
    ]
