# Generated by Django 5.1.8 on 2025-05-07 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_event_exclude_from_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="google_calendar_event_id",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar event ID for syncing. Leave blank to create new event.",
                max_length=255,
                null=True,
            ),
        ),
    ]
