# Generated by Django 5.1.8 on 2025-05-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_event_google_calendar_event_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved/Published"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="pending",
                help_text="Moderation status: pending, approved, rejected, or archived.",
                max_length=20,
            ),
        ),
    ]
