services:
  - type: web
    name: dertown
    env: python
    buildCommand: buildCommand: pip install uv && uv pip install . && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn dertown.wsgi:application
    migrateCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dertown.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com, dertown.org, www.dertown.org