services:
  - type: web
    name: dertown
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dertown.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dertown.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com