databases:
  - name: mysitedb
    plan: free
    databaseName: mysite
    user: mysite
services:
  - type: web
    name: dertown
    env: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn dertown.wsgi:application' 
    migrateCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dertown.settings.production
      - key: SECRET_KEY
        generateValue: true


