# Generated by Django 5.1.9 on 2025-05-12 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0008_location_status_organization_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.URLField()),
                ("last_scraped", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of last scrape (success, error, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, help_text="Error message from last scrape, if any"
                    ),
                ),
                (
                    "import_frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("manual", "Manual Only"),
                        ],
                        default="daily",
                        help_text="How often to automatically import events from this source.",
                        max_length=20,
                    ),
                ),
                (
                    "event_tag",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tag/category to assign to events from this source",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.tag",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this source site",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="events.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_logs",
                        to="ingest.sourcesite",
                    ),
                ),
            ],
        ),
    ]
