# Generated by Django 5.1.9 on 2025-05-12 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_google_calendar_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="parent_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent location (e.g., a city that contains\
                     multiple neighborhoods)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_locations",
                to="events.location",
            ),
        ),
    ]
