# Generated by Django 5.1.9 on 2025-05-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tag_calendar_id_tag_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='calendar_id',
            field=models.CharField(blank=True, help_text='Google Calendar ID for this tag/category             (for subscriptions, embeds, and iCal feeds)', max_length=255, null=True),
        ),
    ]
