# Generated by Django 5.1.9 on 2025-05-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_tag_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.CharField(blank=True, help_text="Event fee, e.g. '$10', 'Free', 'Donation', or a range", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='Is registration or ticket purchase required?'),
        ),
    ]
