# Generated by Django 5.1.9 on 2025-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_fee_event_registration_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved/Published'), ('duplicate', 'Duplicate'), ('archived', 'Archived')], default='pending', help_text='Moderation status: pending, approved, duplicate, or archived.', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved/Published'), ('duplicate', 'Duplicate'), ('archived', 'Archived')], default='pending', help_text='Moderation status: pending, approved, duplicate, or archived.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved/Published'), ('duplicate', 'Duplicate'), ('archived', 'Archived')], default='pending', help_text='Moderation status: pending, approved, duplicate, or archived.', max_length=20),
        ),
    ]
