name: Feature Request
description: Suggest a new feature or enhancement for DerTown.
title: "[Feature] <brief description>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature or improvement!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem or an opportunity? If so, please describe
      description: A clear and concise description of what the problem is. Ex: I'm always frustrated when [...], I've always wished that I could [...]
      placeholder: Describe the problem or opportunity
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Have a thought on what you'd like the solution to be?
      placeholder: Describe your ideal solution
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Have you considered any alternative solutions or features?
      placeholder: List any alternatives
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context or screenshots
    validations:
      required: false 