# Generated by Django 5.1.9 on 2025-05-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcesite",
            name="extraction_function",
            field=models.CharField(
                choices=[
                    ("skileavenworth", "Skileavenworth"),
                    ("iciclebrewing", "Iciclebrewing"),
                    ("cityofleavenworth", "Cityofleavenworth"),
                    ("llm", "Llm"),
                    ("default", "Default"),
                    ("wenatcheeriverinstitute", "Wenatcheeriverinstitute"),
                    ("cascadekodiakathletics", "Cascadekodiakathletics"),
                    ("icca", "Icca"),
                ],
                default="llm",
                help_text="Extraction function to use for this source",
                max_length=50,
            ),
        ),
    ]
