name: Run Django Migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py migrate --settings=dertown.settings.production
        python manage.py collectstatic --noinput --settings=dertown.settings.production 