name: Run Django Migrations

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install uv and project dependencies
      run: |
        pip install uv
        uv venv
        uv pip install .

    - name: Create Required Directories
      run: |
        mkdir -p dertown/static
        mkdir -p staticfiles
        mkdir -p media

    - name: Run Migrations
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py migrate --settings=dertown.settings.production
        python manage.py collectstatic --noinput --settings=dertown.settings.production

    - name: Create Superuser
      if: success()
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_EMAIL }}
        DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
        DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      run: |
        python manage.py createsuperuser --noinput --settings=dertown.settings.production || true 