name: Lint & Format

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Python dependencies
        run: |
          pip install ruff
      - name: Install Node.js dependencies
        run: |
          npm ci || npm install
      - name: Run Ruff (Python lint)
        run: ruff check .
      - name: Run Ruff Format (Python format check)
        run: ruff format --check .
      - name: Run Stylelint (CSS)
        run: npm run lint:css
      - name: Run ESLint (JS)
        run: npm run lint:js
      - name: Run Prettier (format check)
        run: npx prettier --check 'dertown/static/**/*.{css,js,html,md}' 'events/static/**/*.{css,js,html,md}'
      - name: Run Markdownlint (Markdown)
        run: npm run lint:md 